// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOA1uB3soAFia9eprK-qUi9Lgwd6RVeQ',
    appId: '1:5004017647:web:d22a5fe98f58479a54001a',
    messagingSenderId: '5004017647',
    projectId: 'pathplanner-48498',
    authDomain: 'pathplanner-48498.firebaseapp.com',
    storageBucket: 'pathplanner-48498.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcG7B_y_u5uYqPtdklc_rW5mBI4tl05A',
    appId: '1:5004017647:android:098eef1079d8bb2954001a',
    messagingSenderId: '5004017647',
    projectId: 'pathplanner-48498',
    storageBucket: 'pathplanner-48498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDgC4yVoPpaDe2lyqWTRTB6Hw_ZGhd06E',
    appId: '1:5004017647:ios:52fb3275977fbf6554001a',
    messagingSenderId: '5004017647',
    projectId: 'pathplanner-48498',
    storageBucket: 'pathplanner-48498.firebasestorage.app',
    iosBundleId: 'com.example.pathPlanner',
  );
}
