// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-1urtBpQCJ10EjTEL9AQP8UahOHvIbtY',
    appId: '1:1048761680559:web:0d6268c376c430b9d98a5a',
    messagingSenderId: '1048761680559',
    projectId: 'dronetrack-211a2',
    authDomain: 'dronetrack-211a2.firebaseapp.com',
    storageBucket: 'dronetrack-211a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Zuw2LDwaqb89Faapgq5vHUArJPe73pM',
    appId: '1:1048761680559:android:cfd64830d4b5c0b0d98a5a',
    messagingSenderId: '1048761680559',
    projectId: 'dronetrack-211a2',
    storageBucket: 'dronetrack-211a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdSSa1UNYTh_cfOZd4J63Cd2aoJtEn-Mc',
    appId: '1:1048761680559:ios:89cca18575333e14d98a5a',
    messagingSenderId: '1048761680559',
    projectId: 'dronetrack-211a2',
    storageBucket: 'dronetrack-211a2.firebasestorage.app',
    iosBundleId: 'com.example.droneTelemetryAndControls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdSSa1UNYTh_cfOZd4J63Cd2aoJtEn-Mc',
    appId: '1:1048761680559:ios:89cca18575333e14d98a5a',
    messagingSenderId: '1048761680559',
    projectId: 'dronetrack-211a2',
    storageBucket: 'dronetrack-211a2.firebasestorage.app',
    iosBundleId: 'com.example.droneTelemetryAndControls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-1urtBpQCJ10EjTEL9AQP8UahOHvIbtY',
    appId: '1:1048761680559:web:59eb88d22907edb3d98a5a',
    messagingSenderId: '1048761680559',
    projectId: 'dronetrack-211a2',
    authDomain: 'dronetrack-211a2.firebaseapp.com',
    storageBucket: 'dronetrack-211a2.firebasestorage.app',
  );
}
