/// Flutter icons SpinDrone
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpinDrone
///      fonts:
///       - asset: fonts/SpinDrone.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpinDrone {
  SpinDrone._();

  static const _kFontFam = 'SpinDrone';
  static const String? _kFontPkg = null;

  static const IconData spinDrone = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
